// pinturas
const obras = [
{
  id: 1,
  title: "Portrait of Dora Maar",
  category: "Picasso",
  pintor: "Pablo Picasso",
  img: "./img/picasso1.jpg",
  desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
id: 2,
title: "Las Señoritas de Avignon",
category: "Picasso",
pintor: "Pablo Picasso",
img: "./img/picasso2.jpg",
desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
  id: 3,
  title: "The Old Guitarist",
  category: "Picasso",
  pintor: "Pablo Picasso",
  img: "./img/picasso3.jpg",
  desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
id: 4,
title: "Girl Before a Mirror",
category: "Picasso",
pintor: "Pablo Picasso",
img: "./img/picasso4.jpg",
desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
  id: 5,
  title: "The Weeping Woman",
  category: "Picasso",
  pintor: "Pablo Picasso",
  img: "./img/picasso5.jpg",
  desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
id: 6,
title: "Nude, Green Leaves and Bust",
category: "Picasso",
pintor: "Pablo Picasso",
img: "./img/picasso6.png",
desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
  id: 7,
  title: "Girl with a Dove",
  category: "Picasso",
  pintor: "Pablo Picasso",
  img: "./img/picasso7.jpg",
  desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
id: 8,
title: "Guernica",
category: "Picasso",
pintor: "Pablo Picasso",
img: "./img/picasso8.jpg",
desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
  id: 9,
  title: "Life",
  category: "Picasso",
  pintor: "Pablo Picasso",
  img: "./img/picasso9.jpg",
  desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},
{
id: 10,
title: "Untitled",
category: "Picasso",
pintor: "Pablo Picasso",
img: "./img/picasso10.jpg",
desc: `Nació el 25-10-1881 en Málaga, España, murión el 08-04-73 en Mougins, Francia. Movimiento: Cubismo, Poimpresionismo, Neoclasicismo, Surrealismo. Escuela: Ecole de Paris. Obras: 1169`,
},

];
